version: '3.2'

services:

  mysql:
    image: ozakziki/mysql-custom:1.0
    environment:
      MYSQL_ROOT_PASSWORD: passwdrahasia
      MYSQL_DATABASE: dbkuasai
      MYSQL_USER: cilsykuasaiuser
      MYSQL_PASSWORD: cilsykuasaipassword
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - int_net
    deploy:
      placement:
        constraints: [node.role == manager]      
  pma:
    image : ozakziki/pma-custom:1.0
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: passwdrahasia
    depends_on:
      - mysql
    networks:
      - proxy_net
      - int_net
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure    

  proxy:
    image: ozakziki/proxy-custom:1.0
    ports:
      - 80:80
    networks:
      - proxy_net
      - int_net
    deploy:
      replicas: 3
      update_config:
        parallelism: 3
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]    

  web:
    image: ozakziki/web-custom:1.0
    depends_on:
      - mysql
    networks:
      - proxy_net
      - int_net
    volumes:
      - web-data:/var/www/html
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure 

networks:
  int_net:     
  proxy_net:

volumes:
  mysql-data:
  web-data:

