version: '3.2'

services:

  mysql:
    image: ozakziki/mysql-custom:1.0
    secrets:
      - db_root_password
      - db_dba_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: dbkuasai
      MYSQL_USER: cilsykuasaiuser
      MYSQL_PASSWORD_FILE: /run/secrets/db_dba_password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - int_net
    deploy:
      placement:
        #constraints: [node.role == manager]      
        constraints: [node.hostname == node-1]  
  pma:
    image : ozakziki/pma-custom:1.0
    #secrets:
    # - db_root_password
    environment:
      PMA_HOST: mysql
      #PMA_USER: root
      #PMA_PASSWORD_FILE: /run/secrets/db_root_password
    networks:
      - proxy_net
      - int_net
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure    

  proxy:
    image: ozakziki/proxy-custom:1.0
    ports:
      - 80:80
    networks:
      - proxy_net
      - int_net
    deploy:
      replicas: 3
      update_config:
        parallelism: 3
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]    

  web:
    image: ozakziki/web-custom:1.0
    depends_on:
      - mysql
    networks:
      - proxy_net
      - int_net
    volumes:
      - web-data:/var/www/html
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure 


secrets:
  db_root_password:
    external: true
  db_dba_password:
    external: true
networks:
  int_net:     
  proxy_net:

volumes:
  mysql-data:
  web-data:

