version: '3.2'

services:

  mysql:
    image: ozakziki/mysql-custom:1.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passwdrahasia
      MYSQL_DATABASE: dbkuasai
      MYSQL_USER: cilsykuasaiuser
      MYSQL_PASSWORD: cilsykuasaipassword
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - int_net
  pma:
    image : ozakziki/pma-custom:1.0
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: passwdrahasia
    links:
      - mysql
    networks:
      - proxy_net
      - int_net

  proxy:
    image: ozakziki/proxy-custom:1.0
    restart: always
    ports:
      - 80:80
    networks:
      - proxy_net
      - int_net

  web:
    image: ozakziki/web-custom:1.0
    restart: always
    links:
      - mysql
    networks:
      - proxy_net
      - int_net
    volumes:
      - web-data:/var/www/html


networks:
  int_net:
    driver: bridge      
  proxy_net:
    driver: bridge
volumes:
  mysql-data:
  web-data:

